version: '{build}'
pull_requests:
  do_not_increment_build_number: true
image: WMF 5
init:
- ps: Install-PackageProvider NuGet -Force
- ps: (new-object net.webclient).DownloadFile('https://dotnetcli.blob.core.windows.net/dotnet/Sdk/rel-1.0.0/dotnet-dev-win-x64.latest.exe', "c:/dotnet-install.exe")
- cmd: c:\dotnet-install.exe /install /quiet
install:
- ps: Install-Module platyPS -Force -RequiredVersion 0.7.0
- cmd: git submodule update --init --recursive
nuget:
  disable_publish_on_pr: true
build_script:
- ps: $psversiontable
- ps: dotnet --version
- ps: get-packageprovider nuget
- ps: ipmo platyPS -Version 0.7.0 ; get-module -name platyPS
- ps: |
    $env:PATH = "c:\program files\dotnet;$env:PATH"

    $projectFile = "src\Docker.PowerShell\project.json"
    $project =  Get-Content $projectFile -Raw | ConvertFrom-Json
    $version = $project.version

    # Tags do not get build versions.
    if ($env:APPVEYOR_REPO_TAG -ne "true") {
      $version += ".$($env:APPVEYOR_BUILD_VERSION.split("-")[0])"

      # Update the project.json version to include the build number.
      $project.version = $version
      ConvertTo-Json $project -Depth 100 | Out-File -Encoding UTF8 $projectFile
    }

    # Replace module manifest version.
    $manifest = "src\Docker.PowerShell\Docker.psd1"
    (Get-Content $manifest -Raw) -replace "ModuleVersion.+","ModuleVersion = '$version'" | Out-File $manifest
    
    Get-Content $projectFile
    Get-Content $manifest
- ps: dotnet restore
- ps: dotnet build src/Docker.PowerShell/project.json
- ps: dotnet publish -f net46 -o $pwd\bin\net46 -c Release $pwd\src\Docker.PowerShell
- ps: dotnet publish -f netstandard1.6 -o $pwd\bin\netstandard1.6 -c Release $pwd\src\Docker.PowerShell
- ps: New-ExternalHelp -Path src\Docker.PowerShell\Help -OutputPath bin\en-US
- ps: nuget pack src/Docker.PowerShell/Docker.nuspec -BasePath bin -OutputDirectory bin -Symbols -Version $version
artifacts:
- path: bin/*.nupkg
