version: '0.1.0.{build}'
pull_requests:
  do_not_increment_build_number: true
image: Visual Studio 2015
init:
- ps: Install-PackageProvider NuGet -Force
- ps: (new-object net.webclient).DownloadFile('https://dotnetcli.blob.core.windows.net/dotnet/Sdk/rel-1.0.0/dotnet-dev-win-x64.latest.exe', "c:/dotnet-install.exe")
- cmd: c:\dotnet-install.exe /install /quiet
install:
- ps: Install-Module platyPS -Force
- cmd: git submodule update --init --recursive
nuget:
  disable_publish_on_pr: true
build_script:
- ps: $psversiontable | fl *
- ps: dotnet --version
- ps: get-packageprovider nuget
- ps: ipmo platyPS ; get-module -name platyPS
- ps: |
    $env:PATH = "c:\program files\dotnet;$env:PATH"

    $version = $env:APPVEYOR_BUILD_VERSION
    if ($env:APPVEYOR_REPO_TAG -eq "true") {
      # Tags do not get build versions.
      $version = $version.Remove($version.LastIndexOf(".")) + ".0"
    }

    # PowerShell does not support prerelease versions
    $psversion = $version.Split("-")[0]

    $projectFile = "src\Docker.PowerShell\project.json"
    $project =  Get-Content $projectFile -Raw | ConvertFrom-Json
    $project.version = $version
    ConvertTo-Json $project -Depth 100 | Out-File -Encoding UTF8 $projectFile

    $manifest = "src\Docker.PowerShell\Docker.psd1"
    (Get-Content $manifest -Raw) -replace "ModuleVersion.+","ModuleVersion = '$psversion'" | Out-File $manifest
    
    Get-Content $projectFile
    Get-Content $manifest
- ps: dotnet restore
- ps: dotnet build src/Docker.PowerShell/project.json
- ps: dotnet publish -f net46 -o $pwd\bin\net46 -c Release $pwd\src\Docker.PowerShell
- ps: dotnet publish -f netstandard1.6 -o $pwd\bin\netstandard1.6 -c Release $pwd\src\Docker.PowerShell
- ps: New-ExternalHelp -Path src\Docker.PowerShell\Help -OutputPath bin\en-US
- ps: nuget pack src/Docker.PowerShell/Docker.nuspec -BasePath bin -OutputDirectory bin -Symbols -Version $psversion
test_script:
- ps: Register-PSRepository -Name test -SourceLocation $pwd\bin
- ps: Install-Module -Name Docker -Repository test -Force
- ps: Import-Module Docker
- ps: git checkout -- src/Docker.PowerShell/Docker.psd1
- ps: git checkout -- src/Docker.PowerShell/project.json
- ps: git config core.autocrlf true
- ps: New-MarkdownHelp -Module Docker -OutputFolder src\Docker.PowerShell\Help -ErrorAction SilentlyContinue
- ps: Update-MarkdownHelp -Path src\Docker.PowerShell\Help
- ps: |
    git add src\Docker.PowerShell\Help\.
    git status -s
    git diff
    if ((git status -s)){
      throw "Help files do not match updated cmdlets. Please update the help markdown to correspond to the latest changes." 
    }
artifacts:
- path: bin/*.nupkg
